### ISSUE TITLE
这是来自彭英俊的夸奖

### ISSUE THREAD

**Issue by wenyiliangzai** [LONGZR007/IAP-STM32#1]
嗯

**Comment by wenyiliangzai** [comment]
你是不知道干嘛么




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LONGZR007/IAP-STM32"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月27日(星期二) 中午11:08
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [LONGZR007/IAP-STM32] 这是来自彭英俊的夸奖 (#1)





 
Closed #1.

**Comment by LONGZR007** [comment]
说什么呢
